custom_users/urls.py
from django.urls import path

from .views import (

    registration,
    profile_create,
    profile_details,
    profile_edit,
)


app_name = 'custom_users'


urlpatterns = [

    path('registration/', registration, name='registration'),

    path('profile_create/', profile_create, name='profile_create'),

    path('profile_details/<int:id>/', profile_details, name='profile_details'),

    path('profile_edit/', profile_edit, name='profile_edit'),

]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

# from .views import HomeView
from .views import home, checkout

# from products_invoices.views import checkout


urlpatterns = [


    # Admin
    path('admin/', admin.site.urls),

    # Dashboard
    path('', home, name='home'),

    # Stripe
    path('checkout/', checkout, name='checkout'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (products_invoices)
    path('', include('products_invoices.urls', namespace='products_invoices')),

    # Default PATHs
    path('accounts/login/', LoginView.as_view(template_name='custom_users/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='home.html'), name='logout'),

    # path('', include('django.contrib.auth.urls'), name='login'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_name = models.CharField(max_length=250, blank=True, null=True)
    address = models.CharField(max_length=150, blank=True, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    class Meta:
        verbose_name_plural = 'User Profiles'

    def __str__(self):
        return self.user.username

custom_users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput, Select, Textarea, EmailInput, PasswordInput

from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User

        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            # 'first_name': TextInput(attrs={'class': 'form-control'}),
            # 'last_name': TextInput(attrs={'class': 'form-control'}),
            'username': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'password1': PasswordInput(attrs={'class': 'form-control'}),
            'password2': PasswordInput(attrs={'class': 'form-control'}),

        }


class ProfileForm(forms.ModelForm):
    """Creating Profile Form"""
    class Meta:
        """Customize Profile Form"""
        model = Profile

        fields = ['profile_name', 'address', 'image']

        exclude = ['user']

        widgets = {
            'profile_name': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
        }

custom_users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, get_object_or_404, reverse

from .models import Profile
from .forms import SignUpForm, ProfileForm


def registration(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            messages.success(request, 'Registration Successful! Login please...', extra_tags='safe')

            return redirect('login')
    else:
        form = SignUpForm()

    template = 'custom_users/registration.html'
    context = {'form': form}

    return render(request, template, context)


@login_required(login_url='login')
def profile_create(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Profile Created Successfully!', extra_tags='safe')

            return redirect('custom_users:profile_details', id=profile.id)

    template = 'custom_users/profile_create.html'
    context = {'form': ProfileForm()}

    return render(request, template, context)


@login_required(login_url='login')
def profile_details(request, id=None):
    profile = get_object_or_404(Profile, id=id)

    context = {'profile': profile}
    template = 'custom_users/profile_details.html'

    return render(request, template, context)


@login_required(login_url='login')
def profile_edit(request):
    profile = get_object_or_404(Profile, user=request.user)

    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Profile Successfully Updated for {}'.format(request.user.username), extra_tags='safe')

            # return redirect('user/profile-detail/')
            return redirect('custom_users:profile_details', id=profile.id)

    context = {'form':form}
    template = 'custom_users/profile_edit.html'

    return render(request, template, context)

templates/custom_users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
</head>

<body>
<div class="container">
    <h1>Login</h1>

    <hr>
    <!-- Messages -->
    {% include 'messages.html' %}
    <!-- Messages -->
    <hr>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">LOGIN</button>
    </form>

    <br>
    <p>Not registered yet? <a href="{% url 'custom_users:registration' %}">click here</a></p>

</div>
</body>
</html>

templates/custom_users/profile_create.html
{% extends 'base.html' %}

{% block title %}Profile Create{% endblock %}

{% block content %}

    <h1>Create Profile</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">CREATE</button>
    </form>

{% endblock %}

templates/custom_users/profile_details.html
{% extends 'base.html' %}

{% block title %}Profile Details{% endblock %}

{% block content %}

    <h1>Profile Details</h1>

    {% if profile %}

        {% if profile.image %}
            <img src="{{ profile.image.url }}" width="200" height="200" alt="image">
        {% endif %}

        <p>ID: {{profile.user.id}}</p>
        <p>Username: {{profile.user.username}}</p>
        <p>Profile name: {{profile.profile_name}}</p>
        <p>Address: {{profile.address}}</p>
        <p>Email: {{profile.user.email}}</p>

    {% else %}
        <p> You don't have any profile.<a href="{% url 'custom_users:profile_create' %}">Create</a></p>

    {% endif %}

    <a href="{% url 'custom_users:profile_edit' %}"><button type="submit" class="btn btn-danger">EDIT</button></a>

{% endblock %}

templates/custom_users/profile_edit.html
{% extends 'base.html' %}

{% block title %}Profile Edit{% endblock %}

{% block content %}

    <h1>Edit Profile</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-primary">UPDATE</button>
    </form>

{% endblock %}

templates/custom_users/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Registration</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
</head>

<body>
<div class="container">
    <h1>User Registration</h1>
    <br>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">REGISTER</button>
    </form>

    <br>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>

</div>
</body>
</html>