products_invoices/urls.py
from django.urls import path

from .views import (

    create_customer,
    create_product,
    create_invoice,
    single_invoice_details,
    view_all_invoices,

    checkout,
)


app_name = 'products_invoices'


urlpatterns = [

    path('create_customer/', create_customer, name='create_customer'),

    path('create_product/', create_product, name='create_product'),

    path('create_invoice/', create_invoice, name='create_invoice'),

    path('single_invoice_details/<int:id>/', single_invoice_details, name='single_invoice_details'),

    path('view_all_invoices/', view_all_invoices, name='view_all_invoices'),

    # Stripe
    path('checkout/', checkout, name='checkout'),

]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

# from .views import HomeView
from .views import home, checkout

# from products_invoices.views import checkout


urlpatterns = [


    # Admin
    path('admin/', admin.site.urls),

    # Dashboard
    path('', home, name='home'),

    # Stripe
    path('checkout/', checkout, name='checkout'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (products_invoices)
    path('', include('products_invoices.urls', namespace='products_invoices')),

    # Default PATHs
    path('accounts/login/', LoginView.as_view(template_name='custom_users/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='home.html'), name='logout'),

    # path('', include('django.contrib.auth.urls'), name='login'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products_invoices/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    customer_name = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    email = models.EmailField(null=True, blank=True)

    class Meta:
        """Metadata Class"""
        ordering = ['-id']

    def __str__(self):
        return self.customer_name


class Product(models.Model):
    product_name = models.CharField(max_length=150)
    category = models.CharField(max_length=150)
    description = models.TextField(max_length=500)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.product_name


class Invoice(models.Model):

    CURRENCIES = (
        ('Euros', 'Euros'),
        ('USD', 'USD'),
        ('Pounds', 'Pounds'),
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    currency = models.CharField(max_length=20, choices=CURRENCIES, default='Euros')
    date = models.DateField(null=True, blank=True)
    item_code = models.CharField(max_length=10)
    item_description = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    unit_price = models.FloatField(default=0.00)
    discount = models.FloatField()
    # discount = models.FloatField(default=0.0)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.item_code

    @property
    def total(self):
        total_price = self.quantity * self.unit_price - (self.discount / 100)
        # modification = '{:.2f}'.format(total_price)
        # modification = round(total_price, 2)
        return total_price


# class Order(models.Model):
#     invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
#     reference = models.CharField(max_length=10, auto_created=True)
#     customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
#     email = models.EmailField(null=True, blank=True)
#     customer_order_reference = models.CharField(max_length=10)
#     order_date = models.DateField(blank=True, null=True)
#     required_by = models.DateField(blank=True, null=True)
#     delivery_to = models.CharField(max_length=150)
#
#
#     class Meta:
#         ordering = ['-id']
#
#     def __str__(self):
#         return self.reference
#
#     @property
#     def order_total(self):
#         total = self.quantity * self.unit_price - (self.discount / 100)
#         # modification = '{:.2f}'.format(total_price)
#         # modification = round(total_price, 2)
#         return total_price

products_invoices/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import (

    Select,
    Textarea,
    DateInput,
    TextInput,
    EmailInput,
    NumberInput,
    PasswordInput,
    SelectDateWidget,

)

from .models import Customer, Product, Invoice


class CreateCustomerForm(forms.ModelForm):
    class Meta:
        model = Customer

        fields = ['customer_name', 'address', 'email']
        # fields = '__all__'

        widgets = {
            'customer_name': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),

        }


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = ['product_name', 'category', 'description']

        widgets = {
            'product_name': TextInput(attrs={'class': 'form-control'}),
            'category': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),

        }


class CreateInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice

        fields = ['customer', 'currency', 'date', 'item_code', 'item_description', 'quantity', 'unit_price',
                  'discount']

        widgets = {
            'customer': Select(attrs={'class': 'form-control'}),
            'currency': Select(attrs={'class': 'form-control'}),
            'date': SelectDateWidget(attrs={'class': 'custom-select'}),
            'item_code': TextInput(attrs={'class': 'custom-select'}),
            'item_description': Select(attrs={'class': 'custom-select'}),
            'quantity': NumberInput(attrs={'class': 'custom-select'}),
            'unit_price': NumberInput(attrs={'class': 'custom-select'}),
            'discount': NumberInput(attrs={'class': 'custom-select'}),
            # 'total': NumberInput(attrs={'class': 'custom-select'}),

        }

products_invoices/views.py
import json
import stripe
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, get_object_or_404, reverse

from .models import Customer, Product, Invoice
from .forms import CreateCustomerForm, CreateProductForm, CreateInvoiceForm

from custom_users.models import Profile


# Stripe keys
stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
stripe_sec = settings.STRIPE_SECRET_KEY
stripe.api_key = stripe_sec


@login_required(login_url='login')
def create_customer(request):
    if request.method == 'POST':
        form = CreateCustomerForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Customer Created Successfully!', extra_tags='safe')

            return redirect('home')
    else:
        form = CreateCustomerForm()

    template = 'products_invoices/create_customer.html'
    context = {'form': form}

    return render(request, template, context)


@login_required(login_url='login')
def create_product(request):
    if request.method == 'POST':
        form = CreateProductForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Product Created Successfully!', extra_tags='safe')

            return redirect('home')
    else:
        form = CreateProductForm()

    template = 'products_invoices/create_product.html'
    context = {'form': form}

    return render(request, template, context)


@login_required(login_url='login')
def create_invoice(request):
    if request.method == 'POST':
        form = CreateInvoiceForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Invoice Created Successfully!', extra_tags='safe')

            return redirect('products_invoices:view_all_invoices')
    else:
        form = CreateInvoiceForm()

    template = 'products_invoices/create_invoice.html'
    context = {'form': form}

    return render(request, template, context)


@login_required(login_url='login')
def view_all_invoices(request, ):
    all_invoices = Invoice.objects.all()

    # Search
    query = request.GET.get('q')
    if query:
        all_invoices = all_invoices.filter(Q(item_code__icontains=query)).distinct()

    # Paginator
    paginator = Paginator(all_invoices, 4)
    page = request.GET.get('page')
    all_invoices_paginator_data = paginator.get_page(page)

    template = 'products_invoices/all_invoices.html'

    context = {
        'all_invoices': all_invoices,
        'all_invoices_paginator_data': all_invoices_paginator_data,
    }

    return render(request, template, context)


@login_required(login_url='login')
def single_invoice_details(request, id=None):
    invoice_details = Invoice.objects.get(id=id)
    # user = get_object_or_404(User, id=request.user.id)
    # invoice_details = Invoice.objects.get(id=user.id)
    # invoice_details_by_customer = Invoice.objects.filter(customer__id=id)

    context = {
        'invoice_details': invoice_details,
        # 'invoice_details_by_customer': invoice_details_by_customer,

        # Stripe key
        'key': stripe_pub,
    }

    template = 'products_invoices/single_invoice_details.html'

    return render(request, template, context)


# Stripe checkout
def checkout(request):
    amount = 500
    customer = stripe.Customer.create(email=request.POST['stripeEmail'],
                                      source=request.POST['stripeToken'])

    charge = stripe.Charge.create(customer=customer.id, amount=amount, currency='USD',
                                  description='Sample Charge')
    print('status', charge)

    return JsonResponse(charge)

templates/products_invoices/all_invoices.html
{% extends 'base.html' %}

{% block title %}All Invoices{% endblock %}

{% block content %}

    <!-- search -->
    <div class="bg-dark p-5 my-4">
        <div class="container">
            <h3 class="text-white mb-4">Search Invoices</h3>
            <form class="search" action="" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" name='q' placeholder="type item code..."
                        aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-info" class="searchButton">
                            SEARCH
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- search end -->

    <div class="col-md-12">
        <h1>All Invoices</h1>
        <br>
        <!--Start Table-->
        <table class="table table-striped table-bordered table-hover mb-4">
            <thead>
                <tr class="bg-success text-white">
                    <th colspan="14">Invoice List</th>
                </tr>
                <tr>
                    <th>SL.</th>
                    <th>Invoice ID</th>
                    <th>Invoice Code</th>
                    <th>Reference</th>
                    <th>Customer</th>
                    <th>Email</th>
                    <th>Customer Order Reference</th>
                    <th>Order Date</th>
                    <th>Required By</th>
                    <th>Delivery To</th>
                    <th>Order Total</th>
                    <th>Due</th>
                    <th>Currency</th>
                </tr>
            </thead>

            <tbody>
                {% for invoice in all_invoices_paginator_data %}
                    <tr>
                        <td>{{ forloop.counter }}</td>

                        <td>
                            <a href="{% url 'products_invoices:single_invoice_details' invoice.id %}">{{ invoice.id }}</a>
                        </td>

                        <td style="color: red">{{ invoice.item_code }}</td>

                        <td style="color: red">auto</td>

                        <td>{{ invoice.customer.customer_name }}</td>

                        <td>{{ invoice.customer.email }}</td>

                        <td style="color: red">blank</td>

                        <td style="color: red">{{ invoice.date }}</td>

                        <td style="color: red">{{ invoice.date }}</td>

                        <td>{{ invoice.customer.customer_name }}</td>

                        <td>{{ invoice.total }}</td>

                        <td style="color: red">Due</td>

                        <td>{{ invoice.currency }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <!--End Table-->

            <!-- invoice Paginator -->
            <ul class="pagination">
                <li class="page-item">

                    {% if all_invoices_paginator_data.has_previous %}
                        <a class="page-link" href="?page={{ all_invoices_paginator_data.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="false">&laquo;</span>
                        </a>
                    {% endif %}

                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Page {{ all_invoices_paginator_data.number }} of
                        {{ all_invoices_paginator_data.paginator.num_pages }}.</a>
                </li>
                <li class="page-item">

                    {% if all_invoices_paginator_data.has_next %}

                        <a class="page-link" href="?page={{ all_invoices_paginator_data.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
            <!-- invoice Paginator end -->
        </div>

{% endblock %}

templates/products_invoices/create_customer.html
{% extends 'base.html' %}

{% block title %}Create Customer{% endblock %}

{% block content %}

    <h1>Create Customer</h1>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">CREATE</button>
    </form>

{% endblock %}

templates/products_invoices/create_invoice.html
{% extends 'base.html' %}

{% block title %}Create Invoice{% endblock %}

{% block content %}

    <h1>Create Invoice</h1>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">CREATE</button>
    </form>

{% endblock %}

templates/products_invoices/create_product.html
{% extends 'base.html' %}

{% block title %}Create Product{% endblock %}

{% block content %}

    <h1>Create Product</h1>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">CREATE</button>
    </form>

{% endblock %}

templates/products_invoices/single_invoice_details.html
{% extends 'base.html' %}

{% block title %}Invoice Details{% endblock %}

{% block content %}
<div class="container">
    <h1 style="text-align: right">INVOICE</h1>

    <p>{{invoice_details.customer.address}}</p>
    <p style="color: red">Phone: ##</p>
    <p>Email: {{invoice_details.customer.email}}</p>

    <p style="text-align: right; color: red">Order Date: {{invoice_details.date}}</p>
    <p style="text-align: right">Transaction ID: {{invoice_details.id}}</p>

    <br><br>

    <table style="width: 100%; border: 1px solid black">
        <tr style="border: 1px solid black">
            <th>Item Code</th>
            <th>Item Description</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Discount%</th>
            <th style="border: 1px solid black">Total</th>
        </tr>
        <tr>
            <td>{{ invoice_details.item_code }}</td>
            <td>{{ invoice_details.item_description.description }}</td>
            <td>{{ invoice_details.quantity }}</td>
            <td style="color: red">##</td>
            <td>{{ invoice_details.unit_price }}</td>
            <td>{{ invoice_details.discount }}</td>
            <td style="border: 1px solid black">{{ invoice_details.total }}</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td style="border: 1px solid black">#</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Sub Total</td>
            <td style="border: 1px solid black">0.00</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Shipping</td>
            <td style="border: 1px solid black">0.00</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td style="border: 1px solid black">#</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>TOTAL ORDER</td>
            <td style="border: 1px solid black">{{ invoice_details.total }}</td>
        </tr>
    </table>
    <br>
    <hr>
    <h3>Stripe Payment</h3>
    <br>

    <!-- Stripe form -->
    <form action="{% url 'checkout' %}" method="post">
        {% csrf_token %}

        <p>Total Amount is <b style="color: green">{{ invoice_details.total }}</b></p>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key = "{{ key }}"
            data-image = "https://cutt.ly/1wgJms3"
            data-description = "PAYMENT"
            data-amount = "500"
            data-locale = "auto"></script>
    </form>
    <!-- Stripe form end -->
    <br>
    <br>
</div>
{% endblock %}