custom_users/urls.py
from django.urls import path

from .views import (

    registration,
    profile_create,
    profile_details,
    profile_edit,
)


app_name = 'custom_users'


urlpatterns = [

    path('registration/', registration, name='registration'),

    path('profile_create/', profile_create, name='profile_create'),

    path('profile_details/<int:id>/', profile_details, name='profile_details'),

    path('profile_edit/', profile_edit, name='profile_edit'),

]

products_invoices/urls.py
from django.urls import path

from .views import (

    create_customer,
    create_product,
    create_invoice,
    single_invoice_details,
    view_all_invoices,

    checkout,
)


app_name = 'products_invoices'


urlpatterns = [

    path('create_customer/', create_customer, name='create_customer'),

    path('create_product/', create_product, name='create_product'),

    path('create_invoice/', create_invoice, name='create_invoice'),

    path('single_invoice_details/<int:id>/', single_invoice_details, name='single_invoice_details'),

    path('view_all_invoices/', view_all_invoices, name='view_all_invoices'),

    # Stripe
    path('checkout/', checkout, name='checkout'),

]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

# from .views import HomeView
from .views import home, checkout

# from products_invoices.views import checkout


urlpatterns = [


    # Admin
    path('admin/', admin.site.urls),

    # Dashboard
    path('', home, name='home'),

    # Stripe
    path('checkout/', checkout, name='checkout'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (products_invoices)
    path('', include('products_invoices.urls', namespace='products_invoices')),

    # Default PATHs
    path('accounts/login/', LoginView.as_view(template_name='custom_users/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='home.html'), name='logout'),

    # path('', include('django.contrib.auth.urls'), name='login'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
<br>
<div class="container">

    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-success">HOME</button>
    </a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'custom_users:profile_details' request.user.id %}">
            <button type="button" class="btn btn-warning">Profile</button>
        </a>

        <a href="{% url 'logout' %}">
            <button type="button" class="btn btn-danger">Logout</button>
        </a>

        <a href="{% url 'products_invoices:create_customer' %}">
            <button type="button" class="btn btn-primary">Create Customer</button>
        </a>

        <a href="{% url 'products_invoices:create_product' %}">
            <button type="button" class="btn btn-primary">Create Product</button>
        </a>

        <a href="{% url 'products_invoices:create_invoice' %}">
            <button type="button" class="btn btn-primary">Create Invoice (Order)</button>
        </a>

        <a href="{% url 'products_invoices:view_all_invoices' %}">
            <button type="button" class="btn btn-primary">View All Invoices</button>
        </a>

    {% else %}
        <a href="{% url 'login' %}">
            <button type="button" class="btn btn-success">Login</button>
        </a>

        <a href="{% url 'custom_users:registration' %}">
            <button type="button" class="btn btn-primary">Registration</button>
        </a>
    {% endif %}
    <hr>

    <!-- Messages -->
    {% include 'messages.html' %}
    <!-- Messages -->

    {% block content %}


    {% endblock %}

</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <hr>
    <h1>Dashboard</h1>
    <hr>

    <!-- Messages -->
    {% include 'messages.html' %}
    <!-- Messages -->

    <!-- Stripe form -->
    <b style="color: red">Stripe Testing</b>
    <form action="{% url 'checkout' %}" method="post">
        {% csrf_token %}
        <article><label><span>Amount is $5.00</span></label></article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key = "{{ key }}"
            data-image = "https://cutt.ly/1wgJms3"
            data-description = "PAYMENT"
            data-amount = "500"
            data-locale = "auto"></script>
    </form>
    <hr>
    <!-- Stripe form end -->

    <br><br>

    <!-- Dashboard -->
    {% if request.user.is_authenticated %}
        <h3>Welcome <b style="color: green">{{ user.username }}</b></h3><br>
    {% else %}
        <h1 style="color: red">You are not logged in!</h1>
    {% endif %}

    {% if request.user.is_authenticated %}

        {% if profile %}
            <p>
                My Profile <a href="{% url 'custom_users:profile_details' profile.id %}">
                {{ request.user.username }}
            </a>
            </p>

        {% else %}
            <p>
                Create Profile <a href="{% url 'custom_users:profile_create' %}">
                {{ request.user.username }}</a>
            </p>
        {% endif %}

    {% endif %}
    <!-- Dashboard -->

{% endblock content %}

templates/messages.html
<!-- Messages -->
<div>
    {% if messages %}
      <strong>Messages:</strong>
      <ul>
	    {% for message in messages %}
            <li class="{{ message.tags }}">
                {% if 'safe' in message.tags %}
	                {{message|safe}}
                {% else %}
                    {{ message }}
                {% endif %}
            </li>
	    {% endfor %}
      </ul>
    {% endif %}
</div>
<!-- Messages -->